version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: frontend
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: server
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=mongoose_db
      - COUNTRIES_COLLECTION=countries
      - STATES_COLLECTION=states
      - CITIES_COLLECTION=cities
    volumes:
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
      - /docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
